### ISSUE TITLE
A/B Street + Mapbox piggyback demo not working

### ISSUE THREAD

**Issue by ilyabo** [a-b-street/abstreet#1023]
It would be awesome if the Mapbox integration worked!

But it looks like it hasn't been updated for a while. I tried to run the piggyback demo following the  instructions in the README, but it didn't work :(

Running `wasm-pack build --dev --target web -- --features wasm && ./serve_locally.py` leads to this error:

```
error[E0599]: no method named `instantiate` found for struct `synthpop::scenario::Scenario` in the current scope
   --> piggyback/src/piggyback.rs:105:14
    |
105 |             .instantiate(&mut self.sim, &self.map, &mut rng, &mut timer);
    |              ^^^^^^^^^^^ method not found in `synthpop::scenario::Scenario`
```

If I comment out the `spawn_traffic` function body, the app builds and runs, but no abstreet layers are visible and I see this error:

![image](https://user-images.githubusercontent.com/351828/200271984-edf6acc4-dede-4539-87ae-dcb6a7437c05.png)

**Comment by dabreegster** [comment]
Thanks for reporting! I haven't touched this demo in a while, and `cargo check` seems to have not seen the build break... probably because it's a wasm-only target. I just pushed a fix for the compile error; there was a small refactor with starting scenarios a while ago.

The console error looks like you don't have `data/system/us/seattle/maps/arboretum.bin` based on the 404. The deserialization error is then serde trying to parse the 404 HTML response page as a binary file. (It'd probably be better to catch the HTTP error code earlier...)

**Comment by ilyabo** [comment]
Oh thank you so much! I am now able to run it with `montlake.bin` which I do happen to have:
http://localhost:8000/?map=/data/system/us/seattle/maps/montlake.bin

![image](https://user-images.githubusercontent.com/351828/200291624-97e464e8-2f09-44fe-9c73-17804fa2eab7.png)

I want to explore the possibility of integrating the abstreet layer with my flow mapping app which uses Mapbox and Deck.gl.

**Comment by dabreegster** [comment]
Cool, keep me posted! Since this experiment, I've also been trying out just using Rust for "backend" type things and leaving rendering up to Maplibre/leaflet entirely, with stuff like osm2streets.org. But depending exactly what you want to do, the GL canvas mapbox layer is a useful hack. For example, passing individual lane marking detail to mapbox through geojson or something else is very slow and buggy even for small areas, I think because mapbox internally tries to tile and/or simplify everything in a way that doesn't work well for small polygons. Just directly redrawing a big batch of geometry works better for that kind of thing

**Comment by ilyabo** [comment]
Have you considered using deck.gl for rendering the lanes?

**Comment by dabreegster** [comment]
I haven't tried it yet. If there's a way to just specify a whole bunch of colored polygons, it could be helpful.

**Comment by ilyabo** [comment]
Yes, there's the [GeoJSON layer](https://deck.gl/docs/api-reference/layers/geojson-layer) which is just that. I'm guessing it shouldn't be too difficult to reimplement just the rendering logic. If you find that interesting too, maybe we could join forces for working on that.

**Comment by dabreegster** [comment]
I might look into it! I will say, if your goal is just to get the detailed lane rendering in, the intended way forward is https://github.com/a-b-street/osm2streets, not to hook into A/B Street code directly. osm2streets lets you dynamically import an osm.xml clip that you could extract from Overpass (or pre-import), and render it with various levels of detail. It just outputs GeoJSON, so it could be hooked up to deck.gl easily. It's been helpful so far to try and detangle just this piece from the rest of abst

**Comment by ilyabo** [comment]
Thank you Dustin, I will definitely try using osm2streets with deck.gl. And what's the binary format you are using for the lane data? Have you considered GeoArrow? It [can work nicely with deck.gl](https://observablehq.com/@kylebarron/geoarrow-and-geoparquet-in-deck-gl)

**Comment by dabreegster** [comment]
If you're asking about a serialized osm2streets object, it's using serde and can be encoded as JSON, bincode, or any other format: https://github.com/a-b-street/osm2streets/blob/b360a9f126b0f19948d26f91d3d58f19109afc4a/osm2streets/src/lib.rs#L37

A `StreetNetwork` object has a bunch of methods defined on it and exposed in JS that just output GeoJSON strings for rendering right now. GeoArrow might be another output format we could consider
