### ISSUE TITLE
Community and Advertising methods.

### ISSUE THREAD

**Issue by snaildos** [a-b-street/abstreet#104]
Hey there, downloaded the game, played the game, loved the game, but it needs to be better advertise. I am recommend a discord community, and this "game" simulation type thing to be put on steam, Why steam? Advantages for auto updates, Auto Deploys, etc. Please take my advice for this!

**Comment by dabreegster** [comment]
I really like the idea of a Discord for staying in touch with people. I've set aside r/abstreet for that so far, but haven't done much with it.

Steam and itch.io and the like are on my radar, but I think it could be too early to do this. If there's a huge global audience suddenly, then there will be many more bug reports to deal with, especially for people with different platforms / monitors / video card issues. There have been a [flurry](https://github.com/dabreegster/abstreet/issues?q=is%3Aissue+label%3A%22platform+specific+bug%22+) of them already in just a few days, and it's a bit hard to keep up, since most of them I can't personally reproduce on my machine. Too wide an audience this early means much less of my time can be spent working on important things in the [roadmap](https://github.com/dabreegster/abstreet/blob/master/docs/roadmap.md).

So no Steam yet, but certainly at some point in the future.

**Comment by snaildos** [comment]
Sounds good, I understand. Thank you!

**Comment by RuthDanner207** [comment]
FYI: I discovered this project from a Seattle Real Estate Broker’s newsletter (David Warren). Thought you might want to know how the word is getting out.

**Comment by dabreegster** [comment]
Definitely curious in tracking these. I can't find it through google; is the newsletter online?

**Comment by RuthDanner207** [comment]
I’ll forward the email. 

Thanks,
Ruth

**Comment by RuthDanner207** [comment]
As promised. 

Thanks,
Ruth

Sent from my iPhone

Begin forwarded message:

> From: David Warren <david@metropolistgroup.com>
> Date: June 25, 2020 at 10:59:19 AM AKDT
> To: ruthdannerofjuneau@gmail.com
> Subject: Face masks, redlining and celebrating pride at home
> Reply-To: David Warren <david@metropolistgroup.com>
> 
> ﻿
> METROPOLIST NEWS
> 
> 
>  
>  
>  
>  
>  
>  
>  
>  
>  
>  
> I always welcome a chance to connect. If you would like to discuss any of the content of this email, your own situation or just get a cup of coffee please reach out.
> 
> CHEERS!
> David Warren 
> 425-760-8285
> david@metropolistgroup.com
> 
> Copyright © Metropolist, All rights reserved.
> 
> Our mailing address is:
> 2931 First Ave S Suite A
> Seattle, WA 98134
> 
> unsubscribe from this list    update subscription preferences 
> 
>  
> 
> 
> 
> 
> 
> 
> This email was sent to ruthdannerofjuneau@gmail.com 
> why did I get this?    unsubscribe from this list    update subscription preferences 
> METROPOLIST · 2931 1st Ave S · Seattle, WA 98134 · USA 
> 
>

**Comment by dabreegster** [comment]
Cleaning up old issues. Thanks for the ideas here! No immediate plans to release on Steam; we've been organically and slowly growing the audience, mostly through OpenStreetMap communities. When we get to the point of feeling more like "beta" quality, we'll revisit wider launches.

**Comment by ChildishGiant** [comment]
itch might be good since you can automate publishing to it using [itch butler](https://itch.io/docs/butler/) and there are plenty of prototypes on there

**Comment by dabreegster** [comment]
I'm still not sure about widely publicizing A/B Street itself, but [15 minute Santa](santa.abstreet.org) is a spin-off we made in December that is "complete" and actually sort of fun to play. I'll look into launching it there. Thanks for the tip!

**Comment by snaildos** [comment]
Ah! That's amazing! itch would be cool for these open source projects too :)
Regards, SnailDOS

**Comment by dabreegster** [comment]
I'm not in a position where I'm lacking user interest in the project. Closing old issues, but thanks for all the ideas here!
