### ISSUE TITLE
Mac: "game" cannot be opened because the developer cannot be verified

### ISSUE THREAD

**Issue by belt-drive** [a-b-street/abstreet#107]
Trying to launch, get a dialog box saying "'game' cannot be opened because the developer cannot be verified. macOS cannot verify that this app is free from malware." Options are "Move to Trash" or "Cancel". No way to proceed to opening the game.

**Comment by heygirlstyle** [comment]
Try this: https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac

**Comment by dabreegster** [comment]
Thanks for the workaround! From what I can tell, the process to [sign](https://developer.apple.com/developer-id/) the Mac builds to verify they're OK requires Xcode, which is a slight problem, because I don't have a Mac available. It looks like there are ways to make [Github do it](https://github.com/marketplace/actions/import-code-signing-certificates); I'll look into this.

**Comment by belt-drive** [comment]
Solutions in the Apple support article worked, thank you!

**Comment by michaelkirk** [comment]
For posterity, note that this issue is only partially addressed. You can launch from the terminal without a warning, but if you double click on the executable in Finder, the user will still see a similar warning. 

The remained of the work is covered in https://github.com/a-b-street/abstreet/pull/896#issuecomment-1108887256
