### ISSUE TITLE
play_abstreet.bat doesn't do anything

### ISSUE THREAD

**Issue by abirstolov** [a-b-street/abstreet#1093]
This is result I'm getting when running `play_abstreet.bat`

```
C:\abstreet_windows_v0_3_45>set RUST_BACKTRACE=1

C:\abstreet_windows_v0_3_45>./binaries/game.exe  1>output.txt 2>&1
```
And nothing is running.

Env. is Windows 10 /w PowerShell / Cmd shell
Files were extracted from `abstreet_windows_v0_3_45.zip`

**Comment by dabreegster** [comment]
Hi! I don't have a Windows machine handy to work on this, unfortunately.

Things to try:
1) See if an `output.txt` file got created, and send the contents here if so
2) You could try opening a Powershell or other terminal and mimicking what those two commands do, to see if it helps
3) Or run in your browser (slower and some features limited though): https://play.abstreet.org/0.3.45/abstreet.html

**Comment by sjdunbar93** [comment]
In 0.3.43, game.exe was within the root folder and the .bat just called game.exe directly
game.exe 1> output.txt 2>&1

In 0.3.44, game.exe was put into a Binaries folder and play_abstreet is now:
./binaries/game.exe 1> output.txt 2>&1

The output file reads
'.' is not recognized as an internal or external command,
operable program or batch file.

The problem is that the .bat file should use "\" for delimiters instead of "/". If you replace them manually then the game and the subexes work fine. If you manually launch game.exe then the game will exit if you try to enter a subfunction from the game.

**Comment by dabreegster** [comment]
Hi @sjdunbar93, please give https://github.com/a-b-street/abstreet/releases/tag/v0.3.48 a try. I fixed the directory separators, but I'm still not totally sure Windows can handle ".\binaries\foo.exe", or all of the STDOUT/STDERR redirection options. If this new build doesn't work, I might ask your help modifying the .bat files and trying a few more things. I don't have a Windows system available to test this myself

**Comment by sjdunbar93** [comment]
New release appears to run without issue.

**Comment by dabreegster** [comment]
Fantastic, thanks for confirming! Andy is working on making these scripts even more robust, but I'll close out this issue unless someone else has trouble with Windows.
