### ISSUE TITLE
Feature request: "Don't block the box" cameras

### ISSUE THREAD

**Issue by belt-drive** [a-b-street/abstreet#115]
It would be very useful to have some way to keep cars from blocking intersections. Sometimes these lines of cars blocking an intersection can be persistent after every light cycle and hard to prevent. For example, a parking garage entrance immediately after an intersection can cause a persistent line of cars to backup into the intersection and there's not much the user can do about the parking garage.

PS. Apologies if this is not the best way to post feature requests! I couldn't find any way to tag the issue as a feature request myself, since I don't think I have moderation privileges.

**Comment by dabreegster** [comment]
There actually is block-the-box [protection](https://github.com/dabreegster/abstreet/blob/7d4cf4cd5b27bce37cf35d3d8aecf0e3d5148a2f/sim/src/mechanics/intersection.rs#L299), but it's pretty weak. Cars won't start a turn if the lane they're trying to go to is already full. But as you've found, sometimes the lane has plenty of room, but something near the beginning of it is blocked because of parking. That's a temporary problem that'll go away, but it of course causes issues. If you're curious, you can even disable this check by passing `--disable_block_the_box` to `game` in `play_abstreet.sh`

Some ideas:
- improve the block-the-box rule and require there to be space for the vehicle trying to turn at the start of the target lane. the difficulty here is that it could mean cars won't start turns close together when they really ought to. it's a bit hard to predict when someone on a lane might stop
- don't make parallel parking block the lane for so long (`TIME_TO_PARK` is 15s). or maybe for driveways in/out of garages, it should be way lower.

This is a great way to post feature requests; keep them coming! I'm not sure how to change the github settings, but besides, I don't mind triaging them at all

**Comment by belt-drive** [comment]
Very interesting, thank you! I could maybe answer this by hunting through
the code, but I'll take the easy path and ask directly: is the
block-the-box avoidance parameter dependent on the phase of the light
cycle? To your point about making close turns, can you have a high
block-the-box tolerance during the green phase of a light to allow for
close turns that drops when the phase is about to end and the light turns
yellow? That might prevent some blocked intersections but still allow some
blocked intersection problems to persist (since this is obviously a
real-world problem, as demonstrated by Mercer and 9th in Seattle). Again,
not knowing the code, that behavior might already be in there.

And follow-up question, could an intersection editor then include "length
of yellow" as a tunable parameter? Maybe it does already, but I haven't
seen it. I also recognize that adding too many tunable parameters can
degrade user experience and the intersection editor is already very
feature-rich, so there's always a balance.

**Comment by dabreegster** [comment]
The implementation of signals is way simpler than you might expect -- the yellow lights are a lie. :) If there's enough time to complete the turn at full speed assuming there's no blockage in the target lane, a vehicle or pedestrian will [make a run for it](https://github.com/dabreegster/abstreet/blob/eb2be71a65e07c6286a3fc451462218a34e871bb/sim/src/mechanics/intersection.rs#L565). This calculation is easy, because there's instant acceleration. The yellow light is just for rendering in the [last 5s](https://github.com/dabreegster/abstreet/blob/eb2be71a65e07c6286a3fc451462218a34e871bb/game/src/render/traffic_signal.rs#L39).

I'm not sure about exposing parameters to control the block-the-box behavior per intersection. Once the gridlock resolution is fixed properly and nobody gets stuck in a way that's unrealistic, there are maybe some parameters we could tune. They'd probably be hidden from the main UI in some sort of advanced editor. Some of these things would include actuated and adaptive signals (instead of just fixed phases) and timing plans that change for morning/afternoon/weekend rush hours.

**Comment by dabreegster** [comment]
There are other issues focused on the root gridlock problems, closing this one
