### ISSUE TITLE
Improve generated turn geometry

### ISSUE THREAD

**Issue by matkoniecz** [a-b-street/abstreet#178]
https://www.openstreetmap.org/#map=19/50.06483/19.94458&layers=N produced really silly crossing (first of all U turn here should not be possible or it should be possible to ban it, and second - why vehicles are driving through it one by one if it is in stop sign mode? Is it some USA law that only one vehicle may be at the crossing at the same time if stops signs are present? Or is it something added by this game? Because it leads to really stupid effects here. Not sure whatever traffic lights will be a sufficient workaround.)

But one clear bug is that vehicles float outside it, here is their driving path:

![screen02](https://user-images.githubusercontent.com/899988/87103389-2eb76100-c255-11ea-8037-b95c2b274b96.png)

**Comment by dabreegster** [comment]
If I change `onstreet_parking: convert_osm::OnstreetParking::JustOSM`, then this looks way more reasonable:

![Screenshot from 2020-07-09 17-52-45](https://user-images.githubusercontent.com/1664407/87104508-0277f200-c20d-11ea-9d5f-fa4262cdb20b.png)

When road width is very wrong, the intersection geometry becomes ridiculous. Fixing the interior sidewalks on Lubicz would help even more. Those're tagged `sidewalk=separate`, so improving that is blocked on using separate OSM footpaths. I made https://www.openstreetmap.org/changeset/87787847 to explicitly stop the random parking lane assigner from messing up here -- but this is kind of a fundamental problem with randomly guessing where parking lanes are. It'll make some roads much wider, and cause geometry problems.

The traffic signal intersection is smushed against the other one because there's a tiny little https://www.openstreetmap.org/way/24217004 in between. Ideally here A/B Street would automatically eat that road and make one intersection, but getting that to work in general is very hard. Alternatively, we could give up on fixing the geometry, but prevent vehicles from stopping on that tiny little road. https://github.com/dabreegster/abstreet/issues/129#issuecomment-653978731 sums up these two approaches. If it's a valid way to tag it in OSM, it could help to remove this way and link both pieces of Lubibz directly to that node with the traffic signal. I didn't look closely enough.

The driving path looking weird is less important for simulation quality, but is certainly annoying. I'm generating  a bezier curve between the end of the first lane and beginning of the first in a really simple way; it doesn't try to make the curve fit inside the intersection. It usually works fine.

**Comment by dabreegster** [comment]
Marcel cleaned up turn geometry a fair bit back in December
