### ISSUE TITLE
Import a road from A/B Street into Streetmix

### ISSUE THREAD

**Issue by Robinlovelace** [a-b-street/abstreet#386]
I've had a few plays with Leeds since #375 (many thanks for the support with that) and in my most recent escapade have discovered the 'Export to StreetMix' feature, resulting in this for a random segment in the city:

```json
{
  "schemaVersion": 24,
  "segments": [
    {
      "id": "Lane #7348",
      "type": "drive-lane",
      "variant": "inbound|car",
      "width": 2.5
    },
    {
      "id": "Lane #7349",
      "type": "drive-lane",
      "variant": "outbound|car",
      "width": 2.5
    }
  ]
}
```

Aside from suspecting that the lanes are too narrow (I think ~7m is standard for 2 lane road in the UK), which may be an OSM issue, I couldn't find any info or links on how to use this file, the closest I got being this https://dabreegster.github.io/abstreet/map/platform.html?highlight=streetmix#use-cases

I also couldn't see how to use this file when looking at https://streetmix.net/

Not an urgent issue, just thought worth documenting in case use/interest from developer/user perspectives after testing with @temospena (who incidentally was asking about SUMO/abst comparisons but that is for another day/issue).

I can report more observations/questions as I proceed with Leeds if that would be of use/interest. Many thanks for taking a small step towards the gamification of transport planning software that could lead to a big leap in terms of the democratisation.

**Comment by dabreegster** [comment]
This export tool comes from conversations with @louh and @kfarr. The goal is to import a road segment from A/B Street into Streetmix to come up with a more detailed design. It could be particularly useful as a way to "import" any road from OSM into Streetmix, because abst has done some of the tedious work of [inferring](https://github.com/dabreegster/abstreet/blob/master/map_model/src/make/initial/lane_specs.rs) the type of lanes from OSM metadata. Ultimately it'd be great if pressing the export button would just open a browser tab with Streetmix loaded.

I haven't gotten this to work yet; the Streetmix API doesn't have a direct way to create a new street with a JSON specification. So instead, I'm trying to create a new street in Streetmix, then do a `PUT` request to `'https://streetmix.net/api/v1/streets/<ID>` and bring in this JSON slice. I used Chrome's devtools to capture the exact request made by the Streetmix editor when making a change, but I'm still having trouble replaying it. It may be due to the auth cookies not being replayed properly, or with `editCount` or something else in the JSON payload. I'll poke at it again, and if I get it working, figure out a way to make the "export" button give manual instructions for importing into stmix.

> Aside from suspecting that the lanes are too narrow (I think ~7m is standard for 2 lane road in the UK)

OSM doesn't have a way of specifying individual lane width, and the road-wide `width` tag is not used much in practice. So these values are hardcoded guesses currently.

> I can report more observations questions as I proceed with Leeds if that would be of use/interest

Yes, please!

**Comment by Robinlovelace** [comment]
Great, thanks for the quickfire reply @dabreegster, no definitive answers but it make sense and moves things forward.

**Comment by matkoniecz** [comment]
> OSM doesn't have a way of specifying individual lane width, and the road-wide width tag is not used much in practice.

Going by other lane specific tags it would be `width:lanes=3|4` for lanes 3m wide and 4m wide, but it is basically unused https://taginfo.openstreetmap.org/keys/width%3Alanes

See https://taginfo.openstreetmap.org/keys/turn%3Alanes#values https://taginfo.openstreetmap.org/keys/psv%3Alanes https://taginfo.openstreetmap.org/keys/destination%3Alanes#values https://taginfo.openstreetmap.org/keys/hov%3Alanes https://taginfo.openstreetmap.org/keys/bicycle%3Alanes for other lane specific tags
