### ISSUE TITLE
Cars looking for parking create "block circles" that create gridlock

### ISSUE THREAD

**Issue by belt-drive** [a-b-street/abstreet#498]
This is a consistent issue that I've had on the South Seattle map. In the area around Harborview Hospital, north of Yesler, as well as in parts of downtown, cars looking for parking create "block circles" that lead to permanent gridlock that eventually spreads throughout the city. This happens when there are three streets, for triangular layouts in downtown, or four streets, in the case of the image below near Yesler, where drivers are all trying to turn right. They end up completely surrounding a block and are then stuck there forever. This seems to be more common in areas with parking garages where lots of cars are doing funny turning maneuvers on streets with low capacity and lots of intersections.

FWIW, is the Harborview garage actually public parking? It seems like Harborview is strongly over-represented as a destination in the game's traffic model, and I'm wondering if that's because of the parking garage there.

I suppose that leads to a more philosophical question about "public parking." The Harborview garage probably isn't set up as a commuter garage and instead prices parking for short-term visitors to the hospital. Does the model account for something like this? I'm guessing "no", since I don't think the game distinguishes between a commute trip and a "special" trip to a medical center. It also makes me wonder whether the game allows for private parking in commercial areas. Lots of office buildings downtown have some amount of private parking for employees. It seems like many cars in the game model park on First Hill or near the stadiums in Pioneer Square, since that's where public parking is located. I don't have any data to support this claim, but my hunch is that is not a realistic representation of actual weekday commuting behavior (before COVID at least).

<img width="1392" alt="Screen Shot 2021-02-04 at 8 58 50 AM" src="https://user-images.githubusercontent.com/67647924/106928633-3d210a80-66c8-11eb-9164-f10149f2bf28.png">

**Comment by dabreegster** [comment]
Alright, there are a few different problems here. Let's see...

> FWIW, is the Harborview garage actually public parking

Since I don't have any good source for private garage parking capacity, in some maps I make blanket guesses, but in downtown and south_seattle, at some point I made all buildings have as many spots as needed for all driving trips that originate there. In this case, it winds up being 346. The spots actually are private, meaning only trips going to or from the building can use it:
![Screenshot from 2021-02-04 11-38-07](https://user-images.githubusercontent.com/1664407/106946093-83349900-66dd-11eb-8280-0a9b56b4e4ea.png)

> It seems like Harborview is strongly over-represented as a destination in the game's traffic model

The commuter pattern dashboard agrees with you -- 9000 trips to/from there:
![Screenshot from 2021-02-04 11-40-56](https://user-images.githubusercontent.com/1664407/106946397-e4f50300-66dd-11eb-8e82-344ec37017ae.png)

I don't know whether or not this figure is reasonable. Regardless, it comes from Soundcast. If the number's inaccurate, it's not the same type of problem as #89, since Harborview isn't some sprawling campus.

> I don't think the game distinguishes between a commute trip and a "special" trip to a medical center

I need to add this to https://a-b-street.github.io/docs/trafficsim/parking.html. There is a distinction between public and private parking. All street spots and parking lots are public right now, and "free." There are some public off-street spots in buildings, coming from https://data-seattlecitygis.opendata.arcgis.com/datasets/public-garages-or-parking-lots. But most parking in buildings is labeled "private" in the info panel, meaning only trips starting or ending there can park there. So at least in the Harborview case, it's working reasonably.

> my hunch is that is not a realistic representation of actual weekday commuting behavior

You're probably right, and they go that far because of how inaccurate the guesses for number of private parking spots are in their destination buildings. In the layers menu, there's a "parking efficiency" option that shows how far away from their car somebody had to park. All the red dots here mean some very unrealistic behavior is likely happening:
![Screenshot from 2021-02-04 11-51-33](https://user-images.githubusercontent.com/1664407/106947556-61d4ac80-66df-11eb-99b9-c4760a281f4c.png)


And back to the original issue of people circling around in one area all looking for parking: when somebody is close to their destination and needs parking, they greedily (and omnisciently) look for the nearest free spot and go for it. Only when they arrive at that spot do they know if it's still free or not. If someone else got it, the process repeats. A consequence of this is the "parking snake/parade" forming. It's totally unrealistic behavior.  We need to at least add in some randomization to spread people out.

Some things you should try in the short-term:
- Run the game with the `--infinite_parking` option, which effectively makes all car trips go directly between buildings and never have a walking-to-parking phase. While there are so many problems with how parking is modeled, it's a little bit reasonable to just give up on trying.
- I know you're interested in studying large areas, but if you can narrow down your study area at all, it really helps. Recently we got the area around [Rainier Valley](http://abstreet.s3-website.us-east-2.amazonaws.com/dev/game/?--dev&seattle/scenarios/rainier_valley/weekday.bin) totally working for #446, a possible blog post with SNG exploring how SDOT's new maximum signal cycle lengths might mess with walks. It's so much easier for me to concentrate on the few problems that break a small map than to try to tackle everything at once, and having intermediate progress of getting small maps going is nice.

What I'll work on for this bug:
- Filling out the docs to describe how parking works right now
- Coming up with a simple rule for randomizing which spot somebody goes for, to break up the parades

**Comment by dabreegster** [comment]
> Run the game with the --infinite_parking option

Oh yeah, I should say how to do this. If you open `play_abstreet.bat` in a text editor, change `game.exe 1> ..\\output.txt 2>&1` to `game.exe --infinite_parking 1> ..\\output.txt 2>&1`. If you're on Mac, it's `play_abstreet.sh`, and the last line should become `RUST_BACKTRACE=1 ./game --infinite_parking 1> ../output.txt 2>&1`

**Comment by dabreegster** [comment]
I can't say I enjoy writing docs, but the results sure are nice to have around: https://a-b-street.github.io/docs/trafficsim/parking.html

Adding some randomization to the spot selection might not be so hard; I'll try to have a go today or tomorrow.

**Comment by belt-drive** [comment]
Wow, excited to see the Rainier Valley map. It looks like that may have been added since the last time I checked in. Thanks for both of the suggestions for quick fixes @dabreegster

**Comment by dabreegster** [comment]
I think both problems raised in this issue -- the parking "snakes" and the general lack of explanation about how parking works -- are now solved, so closing. We're making progress on the stuck cars, hopefully have news tomorrow!
