### ISSUE TITLE
Game crashed

### ISSUE THREAD

**Issue by Anjun93** [a-b-street/abstreet#636]
Hi, I tried the case of Hiroshima, Japan. It crashed every time. Please check it. 
Here is the output.txt:
[output.txt](https://github.com/a-b-street/abstreet/files/6412975/output.txt)

**Comment by dabreegster** [comment]
Could you please send the `Hiroshima_Univerisity\input_agent.csv` file from grid2demand that you're importing? The simulation is crashing `At 07:18:29.0 on Lane(LaneID(715)), laggy head Car #4477 isn't the last on the lane; it's Car #2847', sim\src\mechanics\driving.rs:747:17`, and it's easiest if I can reproduce this locally. Thanks!

**Comment by dabreegster** [comment]
Edit: Never mind, I just found https://github.com/Anjun93/Global_Data_Set/tree/main/university_campus/Hiroshima_Univerisity. I'll look into this.

**Comment by Anjun93** [comment]
Cool! Thank you!



     Anjun Li


Ph.D. Candidate | Transit Network Design
National United Engineering Laboratory of Integrated and Intelligent Transportation&nbsp;
School of Transportation and Logistics
Southwest Jiaotong University


Visiting scholar
National Center for Smart Growth Research &amp; Education
School of Architecture, Planning &amp; Preservation
University of Maryland&nbsp;

         
     
 

&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "a-b-street/abstreet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月3日(星期一) 晚上11:21
***@***.***&gt;;
抄送:&nbsp;"Anjun ***@***.******@***.***&gt;;
主题:&nbsp;Re: [a-b-street/abstreet] Game crashed (#636)





 
Edit: Never mind, I just found https://github.com/Anjun93/Global_Data_Set/tree/main/university_campus/Hiroshima_Univerisity. I'll look into this.

**Comment by dabreegster** [comment]
Near lane 715 from the error message, I noticed many circular intersections like this:
![Screenshot from 2021-05-03 11-25-31](https://user-images.githubusercontent.com/1664407/116916544-528fcd00-ac02-11eb-8c8a-f5ffdba8f7fc.png)
These happen when the A/B Street importer gives up on generating intersection geometry, because of something very broken in OpenStreetMap. Exploring some of this area in OSM, the problem is overlapping ways:
https://www.openstreetmap.org/way/884586149 overlaps with https://www.openstreetmap.org/way/115818058
![Screenshot from 2021-05-03 11-27-38](https://user-images.githubusercontent.com/1664407/116916741-94207800-ac02-11eb-9c58-f8cd0e5e9d7e.png)

The importer also warns about this, but proceeds anyway and does the best it can. I'm going to fix these problems in OSM, re-import, and see if the crash still happens.

**Comment by Anjun93** [comment]
Thank you for pointing the issue out! Previously, I tried to import the .osm file of Hiroshima with one_step_import.exe in abstreet_windows_v0_2_40. The game can run the same case without crash, even though the circular intersections exist. I'll try later after the problems fixed.

**Comment by dabreegster** [comment]
I'm not sure why the older version didn't hit this problem. In any case, I've made some [fixes in OSM](https://www.openstreetmap.org/user/Dustin%20C/history#map=2/44.5/10.4). I can now simulate the full day without problems. I'll note that a large number of trips do get cancelled because the cars run out of available parking. You can run the simulation with [--infinite_parking](https://a-b-street.github.io/docs/howto/asu.html#a-shortcut-and-improving-the-simulation-in-tempe) to disable parking simulation, or if you have data about the capacity of parking lots and garages on campus, we could add it to OSM.

Unfortunately due to my laptop failing, I can't easily upload the fixed Hiroshima map for a few days. You can extract the .osm file yourself again as you were doing previously, or manually gunzip and copy the attached file, overwriting `data/system/jp/hiroshima/maps/uni.bin`
[uni.bin.gz](https://github.com/a-b-street/abstreet/files/6423660/uni.bin.gz)

**Comment by Anjun93** [comment]
I just tried it. The simulation can run without problems. Thank you, Dustin!
