### ISSUE TITLE
Consider using `sort_unstable` over `sort`

### ISSUE THREAD

**Issue by vks** [a-b-street/abstreet#650]
Currently, we mostly use `sort` and friends. However, I suspect that in most cases we don't require a stable sort, so `sort_unstable` might be a better choice?

**Comment by dabreegster** [comment]
Generally when building the map (`convert_osm`, `importer`, `map_model`) or running the simulation (`sim`), we take extreme care to be totally deterministic. That's why there's so many `BTreeMap`s instead of `HashMap`s.

So https://doc.rust-lang.org/std/vec/struct.Vec.html#method.sort_unstable mentions it does some randomization, but with a fixed seed to preserve determinism. The question is, is it OK to reorder elements that're equal under the comparison? That one will be case-by-case. I can audit the ~60ish places at some point.

**Comment by vks** [comment]
To me it sounds like `sort_unstable` is still deterministic, so determinism should not be a problem? But sure, we need to review whether reordering "equal" elements is fine.

> That's why there's so many BTreeMaps instead of HashMaps.

Depending on what performance characteristics we need, the `indexmap` crate might be a great alternative, too. I think `std::collections::HashMap` also supports determinism via `HashMap::with_hasher`.

**Comment by dabreegster** [comment]
> That's why there's so many BTreeMaps instead of HashMaps

Most of the large uses in [map_model](https://github.com/a-b-street/abstreet/blob/4f05d818b9a3b98918a18ce944491b3c3f587191/map_model/src/lib.rs#L86) are `lanes`, `turns`, `stop_signs`, `traffic_signals`. Most commonly we're just doing lookup, so ideally O(1). We tend to iterate over all of them for setting the simulation / UI, but it's less frequent. Fast mutation isn't important, because it almost never happens after initial import.

The other big use is [sim Analytics](https://github.com/a-b-street/abstreet/blob/4f05d818b9a3b98918a18ce944491b3c3f587191/sim/src/analytics.rs#L16). I think deterministic order is only important here for the diff testing to detect if changes to code/maps actually caused different results in the simulation, but there might also be some stats aggregation in the UI that assumes deterministic iteration. Also for the record, `Analytics` is a mess; some of the fields are partly redundant with each other.

The other map-related perf thing to note is [FixedMap](https://github.com/a-b-street/abstreet/blob/4f05d818b9a3b98918a18ce944491b3c3f587191/sim/src/mechanics/driving.rs#L28), defined [here](https://github.com/a-b-street/abstreet/blob/4f05d818b9a3b98918a18ce944491b3c3f587191/abstutil/src/collections.rs#L307). Apparently the perf benefit was pretty awesome: 491f4bbffe9fb51201080bb9cdf725fae77028c0

**Comment by dabreegster** [comment]
No plans to do anything here, closing
