### ISSUE TITLE
Crash when jumping to trip time in the past.

### ISSUE THREAD

**Issue by michaelkirk** [a-b-street/abstreet#684]
Crash when clicking on this button to jump back to a trip that's already happened. (Jumping forward to a future trip works fine)

<img width="430" alt="Screen Shot 2021-06-23 at 9 18 53 AM" src="https://user-images.githubusercontent.com/217057/123133084-3d663c00-d404-11eb-9015-2567105aba22.png">

```
thread 'main' panicked at 'launch_info_panel for some tab immediately tried to execute a transition', game/src/common/mod.rs:296:13
stack backtrace:
   0: std::panicking::begin_panic
   1: game::common::CommonState::launch_info_panel
   2: core::ops::function::FnOnce::call_once{{vtable.shim}}
   3: widgetry::app_state::App<A>::execute_transition
   4: widgetry::app_state::App<A>::execute_transition
   5: widgetry::app_state::App<A>::event
   6: widgetry::event_ctx::EventCtx::no_op_event
   7: widgetry::app_state::App<A>::event
   8: widgetry::event_ctx::EventCtx::no_op_event
   9: widgetry::app_state::App<A>::event
  10: widgetry::event_ctx::EventCtx::no_op_event
  11: widgetry::app_state::App<A>::event
  12: std::panic::catch_unwind
  13: widgetry::runner::State<A>::event
  14: widgetry::runner::run::{{closure}}
  15: <winit::platform_impl::platform::app_state::EventLoopHandler<T> as winit::platform_impl::platform::app_state::EventHandler>::handle_nonuser_event
  16: winit::platform_impl::platform::app_state::Handler::handle_nonuser_event
  17: winit::platform_impl::platform::app_state::AppState::cleared
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: <unknown>
  27: <unknown>
  28: winit::platform_impl::platform::event_loop::EventLoop<T>::run
  29: winit::event_loop::EventLoop<T>::run
  30: widgetry::runner::run
  31: game::main
```

This panic was added in a390f72a1cd0e79ca5a85a74831d272a10e4e9de

And there's this comment:

```
// When executed, this assumes the SandboxMode is the top of the stack. It'll
// reopen the info panel, then launch the jump-to-time UI.
```

So it seems we are indeed trying to do exactly what the panic tells us we shouldn't be trying to do. I looked for a bit, but there seems to be a lot of context around this change.  Do you have any insight into this contradiction @dabreegster?

**Comment by dabreegster** [comment]
Hmm, this crash only seems to happen when there's prebaked data and the map is edited. It's fine otherwise. Looking into it

**Comment by michaelkirk** [comment]
> seems to happen when there's prebaked data and the map is edited

Ah interesting! I indeed am viewing the broadmoor proposal when this occurs. I know that it was working when I was working on the write up draft maybe 6 weeks ago.

**Comment by dabreegster** [comment]
I am having some trouble detangling this hairball. :P  Let's trace through...

- Clicking that button decides to warp to some time and open the info panel for a trip: https://github.com/a-b-street/abstreet/blob/799fdfbbc0c6748cde694df2ac1b8424c8a32c7e/game/src/info/mod.rs#L548
- Since we're going to the past, we reset everything with `SandboxMode::async_new`, then open the info panel for the trip, then time warp forwards

I don't think the assumption about the SandboxMode on top of the stack is wrong; we would see a crash with the downcast in that case. The problem is that `launch_info_panel` for the trip returns `details.stop_immediately`. That's filled out in only two cases, both when a trip panel needs access to an unedited `Map` to compare routes. I think the problem is that `app.primary.calculate_unedited_map` is returning a transition there.

Here's the experiment:
1) With the proposal loaded, first click some other trip and toggle before/after. This should force us to do `calculate_unedited_map` and cache it.
2) Then time-warp to the past

And indeed... it works! I think the fix is to force `calculate_unedited_map` to run before we launch the info panel. It should be possible to squeeze in that transition before we even reset sandboxmode.
![screencast](https://user-images.githubusercontent.com/1664407/123139998-a8ffd780-d40b-11eb-9259-e2c52a9bb5d4.gif)


But there's another bug unearthed: clicking the "before/after" button actually loses the state that one of the trips is opened up for details. I'll dig into that next..

**Comment by dabreegster** [comment]
The crash should be fixed; let me know if the problem/solution isn't clear. Time warping from info panels really stresses the stack-of-states abstraction.

I'll look into the before/after bug next

**Comment by michaelkirk** [comment]
Warping now works as I expect. Thank you!
