### ISSUE TITLE
Line plots always use imperial units

### ISSUE THREAD

**Issue by dabreegster** [a-b-street/abstreet#692]
https://github.com/a-b-street/abstreet/blob/15390914531c65bf4313aaef32094869b0043e02/widgetry/src/widgets/plots.rs#L137

How can we get at `UnitFmt` here? Probably just need to take it in `PlotOptions` and plumb it through.

Good small task / intro to Rust.

**Comment by bowiechen** [comment]
Hi @dabreegster, I'm new to this project and Rust in general. I'd like to scope out this issue and see if I am a good fit for building this task out. 

# Conceptualization
What exactly is the goal here? My interpretation of your comment in this task and in #693 is that this `prettyprint` function currently only plots in imperial units because of the [hard-coded `metric: false` ](https://github.com/a-b-street/abstreet/blob/15390914531c65bf4313aaef32094869b0043e02/widgetry/src/widgets/plots.rs#L137). You're proposing that we change that and allow users to use `PlotOptions` to control the plotted units, is that correct?

# Plan of Action
Assuming that is correct, here's a rough outline of how I'd do this:
- Add a field in the `PlotOptions` struct named `metric` (maybe make it default false to maintain backwards compatibility?)
- Modify `prettyprint(self)` in the code you linked and add a parameter to pass the flag into prettyprint. Perhaps we could just make the function borrow the `PlotOptions` variable? That would probably future-proof the design. 
- Find instances of uses of `PlotOptions` where any of the two axes are `Distance` and find their `prettyprint` methods to pass in `opts` variable. 

# Question: How to Test?
If the above sounds good to you, what would be a good way to test this change? Ideally, I'd like some pointers to add unit tests and UI "integration" tests to see the chart in action.

**Comment by dabreegster** [comment]
Hi @bowiechen! Thanks for your interest in this task.

> You're proposing that we change that and allow users to use PlotOptions to control the plotted units, is that correct?

Yes. To be more specific, users can already change between metric/imperial using the settings:
![Screenshot from 2021-07-17 18-31-40](https://user-images.githubusercontent.com/1664407/126052976-1754c2ae-1b23-4068-8828-c4232dac00c0.png)
![Screenshot from 2021-07-17 18-31-57](https://user-images.githubusercontent.com/1664407/126052982-67e152fb-5a07-45ed-83df-eb4f28a7dcc1.png)
The goal is to make axis labels respect this unit.

> Add a field in the PlotOptions struct named metric

I would recommend embedding [UnitFmt](https://github.com/a-b-street/abstreet/blob/f85f42a614ae390a1d94c6a279c116cbe6afa4f3/geom/src/lib.rs#L68), in case we later add more ways to configure how some quantities are printed.

> Perhaps we could just make the function borrow the PlotOptions variable?

Yes, I think changing to `fn prettyprint(self, opts: &PlotOptions) -> String` would be best.

> Find instances of uses of PlotOptions where any of the two axes are Distance and find their prettyprint methods to pass in opts variable.

I don't think there's a reasonable default option for metric/imperial; we should just set `UnitFmt` in every place that `PlotOptions` is created. So `pub fn filterable() -> PlotOptions` and `fn fixed` should change to take `UnitFmt`, and the few other places directly creating `PlotOptions` should also set it. I haven't checked carefully, but I think all of the places should have easy access to `app.opts.units`, so the existing Settings panel will control everything.

> Ideally, I'd like some pointers to add unit tests and UI "integration" tests to see the chart in action.

Unfortunately we don't have anything like this set up. Unit tests are great for checking how `Distance` gets stringified with different settings, since it's easy to specify the input and output. https://github.com/a-b-street/abstreet/blob/f85f42a614ae390a1d94c6a279c116cbe6afa4f3/geom/src/distance.rs#L255 is an example of something like that. The best we've got right now is just manually trying it out:

1) Set the units to imperial with Settings
2) Open a walking trip and look at the elevation profile
3) Change the settings to metric
4) Repeat

I haven't personally worked with any codebase that has automated UI integration tests, though I've heard of them. If you have any experience and recommend one that we could use for inspiration, maybe it's something worth looking into it.

(https://a-b-street.github.io/docs//tech/dev/testing.html has some notes about tests in the rest of A/B Street, but not much about UI)

**Comment by bowiechen** [comment]
Hey @dabreegster, this might be a noob Rust question, but I couldn't, for the life of me, figure it out. 

I'm attempting to change the signature of the `Axis` trait to `fn prettyprint(self, opts: &PlotOptions) -> String`.

```
error[E0107]: missing generics for struct `PlotOptions`
  --> widgetry/src/widgets/plots.rs:42:33
   |
42 |     fn prettyprint(self, opts: &PlotOptions) -> String;
   |                                 ^^^^^^^^^^^ expected 2 type arguments
   |
note: struct defined here, with 2 type parameters: `X`, `Y`
  --> widgetry/src/widgets/plots.rs:8:12
   |
8  | pub struct PlotOptions<X: Axis<X>, Y: Axis<Y>> {
   |            ^^^^^^^^^^^ -           -
help: use angle brackets to add missing type arguments
   |
42 |     fn prettyprint(self, opts: &PlotOptions<X, Y>) -> String;
   |                                            ^^^^^^
```
`PlotOptions` takes two arguments (types for X and Y axes), but since `prettyprint` is in the `Axis` trait, there's really no way of knowing what the type of other axis... is there?

**Comment by dabreegster** [comment]
Ahh you're right. The types would be recursive the way we're trying to set it up -- `Axis<X>` and `Axis<Y>` both depending on `PlotOptions<X, Y>`. That doesn't make any sense.

Let's just pass in `UnitFmt` to `prettyprint` instead. And actually, you can make it derive [Copy](https://doc.rust-lang.org/std/marker/trait.Copy.html) to simplify things and avoid having to pass `&UnitFmt` or anything like that. It's just two bools.

**Comment by bowiechen** [comment]
I need help with [these two lines](https://github.com/a-b-street/abstreet/blob/master/widgetry/src/widgets/line_plot.rs#L201-L202). It seems that no `UnitFmt` is easily accessible within scope. 

Perhaps we could add `UnitFmt` to `GfxCtx`? But I feel like that's going to become a sprawling change... It _might_ make sense though! In prod/master, if I open a pedestrian's info box, the open settings to toggle units and apply the settings, the pedestrian's info box still retains the old unit. If the graphics context holds a reference/copy to `UnitFmt` though, a call to `redraw` could solve this issue.

**Comment by dabreegster** [comment]
> I need help with these two lines. It seems that no UnitFmt is easily accessible within scope.

In `LinePlot::new_widget`, we can save `opts.units` to the `LinePlot` struct and later use it in `draw`. In other words, the plot options set initially continue to be used to draw tooltips.

> if I open a pedestrian's info box, the open settings to toggle units and apply the settings, the pedestrian's info box still retains the old unit

I think this is a limitation we'll have to live with; if you change the settings, you may need to close the info box and reopen it. Putting the settings in `GfxCtx` would help with the tooltips, but the axis labels would stay the same, because they're drawn just once upon creation. More generally, some of the UI automatically refreshes itself, usually as simulation time passes. But not everything is responsive to window resizing, color scheme changing, etc. It would be nice if it were, but the [framework](https://a-b-street.github.io/docs//tech/dev/ui.html) we've built doesn't make that easy.

**Comment by gedkott** [comment]
https://github.com/a-b-street/abstreet/pull/758
