### ISSUE TITLE
Prevent/explain panics by replacing uses of `Option::unwrap` and `Result::unwrap`

### ISSUE THREAD

**Issue by eviltak** [a-b-street/abstreet#71]
The game panics when trying to open up the settings menu during the tutorial when running from source. The panic is due to a call to `Option::unwrap` in `Dropdown::new`, when the function is unable to find the default value for the dropdown in the choices vector. This is one of 494 uses of `Option::unwrap`. Ideally we would want to replace all of these uses with calls to non-panicking methods like `unwrap_or`, error propagation (when `Result`s are used) or, when panics are unavoidable/desired, `expect` with a detailed error message.

**Comment by dabreegster** [comment]
Note for later: one example is turn conflict doing Polyline intersection. If the two PL's are exactly equal, this method panics, because the caller has done something really wrong and shouldn't paper over that. Ideally we'd plumb context to point to the turn ID or some way of finding the issue. Maybe return Result<Option<...>, ...>?

**Comment by dabreegster** [comment]
Just overhauled a ton of geometry code causing many of these problems. There's still lots left to do.

**Comment by dabreegster** [comment]
We treat any reported crash as a highest-priority bug and fix it ASAP. I think our error handling hygiene has gotten generally better. I could keep this issue around to do some kind of mass audit, but that's not likely happening, so closing for now.
