### ISSUE TITLE
Sidewalks are bidirectional, why aren't crosswalks?

### ISSUE THREAD

**Issue by mdejean** [a-b-street/abstreet#813]
Crosswalks and other walking turns are currently duplicated with one being from each sidewalk. This results in some effort to avoid double-rendering like 
https://github.com/a-b-street/abstreet/blob/master/map_gui/src/render/intersection.rs#L58 
and some double rendering at 
https://github.com/a-b-street/abstreet/blob/master/map_gui/src/render/traffic_signal.rs#L149
which afaik is the only usage of other_crosswalk_ids.

This would require changes to `connectivity/walking.rs` and the pathfinder to create and use `ContraflowTurn`/`ContraflowMovement` for walking turns.

**Comment by dabreegster** [comment]
Great question. I think it's an early design decision that we should
change, in the way you identified. Originally I was planning to create two
sidewalk lanes and retain the one-way property of all lanes. I guess I
decided to just do that for turns, but indeed the simulation and
pathfinding layer later got the contraflow options.

Let me know if you want to do this refactor. I'll have time later today to
catch up on them other PR, followed by another few days of utter chaos.

**Comment by dabreegster** [comment]
Other notes about doing this: We should do the same for `SharedSidewalkCorner` to be consistent. It shows up less in things like the simulation, because by construction there are never any conflicting movements.

I thought the [traffic signal JSON format](https://a-b-street.github.io/docs/tech/dev/formats/traffic_signals.html) might need to change for this, but it looks like no -- I'd just expect the exported files to stop containing a duplicate crosswalk.
