### ISSUE TITLE
👋 you might find a project interesting

### ISSUE THREAD

**Issue by jasikpark** [a-b-street/abstreet#863]
- https://github.com/sharedstreets /  https://sharedstreets.io/
- https://www.jwz.org/blog/2022/02/crosswalks/

**Comment by dabreegster** [comment]
Hello, and thanks for the links! I've been following Shared Streets for a bit -- the CurbLR spec is nice, but I haven't seen many cities publishing things like street parking rules with it yet. (At least openly)

The SF crosswalk data is neat -- if it's ever in OSM or in GeoJSON or something, we could plug it into the #795 experiment

Since it looks like you're fairly into web dev, a question. I hacked together a horrible way for people to share A/B Street proposals (just big JSON blobs) by uploading a [tiny Go server](https://github.com/a-b-street/yimbyhoodlum), but the uploaded proposals are immutable and anonymous, because I don't have time to put together or operate any sort of user account system. Any recommendations for something super easy to let people log in (with existing google/FB/whatever SSO accounts are typically used), upload JSON blobs somewhere, and have basic permissions around viewing, deleting, overwriting, etc?

**Comment by jasikpark** [comment]
uhh i dunno - let me think about it!

**Comment by jasikpark** [comment]
mmmm maybe a wiki system? or just github sorta thing? something like TinyWiki?

a discord could be cool in general for the project :p
